### PR TITLE
Revert "Feature better replace"

### PR DESCRIPTION
**Pull request by mitzey234**
I've having issues with the visual studio file, I can't build it due to a pile of required files seeming to be missing, that or the definition for some of your custom classes is missing. Please check @Undid-Iridium 
image

### CODE REVIEW

**Comment by Undid-Iridium** [comment]
image

https://github.com/Undid-Iridium/SharedLogicOrchestrator

Let me know if you don't have access to the repo

It also includes debug filters, so you can specify what level of information. I would recommend doing that over the alternative just general debug. Eventually I will probably do a PR to Exiled for them to have a better logging system

**Comment by mitzey234** [comment]
I do need access

**Comment by Undid-Iridium** [comment]
You probably need to check your email, I sent it a long time ago, I will send again though

**Comment by mitzey234** [comment]
It did expire, I've got it now and it is building now, I'll bring these changes back over when I finish with today's update. Same goes for 035

**Comment by Undid-Iridium** [comment]
No worries, If you need help testing to make sure it works I am available later

**Comment by mitzey234** [comment]
As long as you you were able to test DC replace working as well as 035, I trust everything should just work

**Comment by Undid-Iridium** [comment]
It should, as far as I tested; however, that was a exiled 5 beta 5, we'll see what happens given the changes to exiled

**Pull request merged**
